---
development:
  DB_KEY:       <replace with crypto key `rake generate:db_key`>
  MSG_KEY:      <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: <provision key from SendGrid>
  SIGNING_KEY:  <replace with signing key from `rake generate:signing_keypair`>
  VERIFY_KEY:   <replace with verify key from `rake generate:signing_keypair`>

test:
  DB_KEY:       <replace with crypto key `rake generate:db_key`>
  MSG_KEY:      <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: <provision key from SendGrid>
  SIGNING_KEY:  <replace with signing key from `rake generate:signing_keypair`>
  VERIFY_KEY:   <replace with verify key from `rake generate:signing_keypair`>
